---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mysql-vm
  name: mysql-vm-svc
spec:
  ports:
  - name: mysql-tcp
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    vm.kubevirt.io/name: mysql-vm
  type: ClusterIP
